# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KalpSetup.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1383, 799)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 1439, 791))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 510, 1251, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 911, 21))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(1060, 30, 61, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(1130, 30, 61, 20))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 70, 931, 31))
        self.textEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(1070, 70, 41, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(1130, 70, 71, 30))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(1230, 40, 141, 391))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 70, 22))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Name = QtGui.QComboBox(self.groupBox_5)
        self.Name.setGeometry(QtCore.QRect(20, 50, 87, 21))
        self.Name.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Name.setMaxVisibleItems(10)
        self.Name.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 70, 22))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Baud = QtGui.QComboBox(self.groupBox_5)
        self.Baud.setGeometry(QtCore.QRect(20, 90, 87, 21))
        self.Baud.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Baud.setObjectName(_fromUtf8("Baud"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(20, 110, 70, 22))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Data_Size = QtGui.QComboBox(self.groupBox_5)
        self.Data_Size.setGeometry(QtCore.QRect(20, 130, 87, 21))
        self.Data_Size.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Data_Size.setObjectName(_fromUtf8("Data_Size"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 70, 22))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Parity = QtGui.QComboBox(self.groupBox_5)
        self.Parity.setGeometry(QtCore.QRect(20, 170, 87, 21))
        self.Parity.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Parity.setObjectName(_fromUtf8("Parity"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 91, 22))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(20, 230, 70, 22))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.Mode = QtGui.QComboBox(self.groupBox_5)
        self.Mode.setGeometry(QtCore.QRect(20, 250, 87, 21))
        self.Mode.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Mode.setObjectName(_fromUtf8("Mode"))
        self.Open_3 = QtGui.QPushButton(self.groupBox_5)
        self.Open_3.setGeometry(QtCore.QRect(20, 300, 102, 30))
        self.Open_3.setObjectName(_fromUtf8("Open_3"))
        self.Handshake = QtGui.QComboBox(self.groupBox_5)
        self.Handshake.setGeometry(QtCore.QRect(20, 210, 87, 21))
        self.Handshake.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Handshake.setObjectName(_fromUtf8("Handshake"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(130, 50, 1081, 431))
        self.textEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(1250, 500, 121, 121))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("logos/KalpLogo.bmp")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 20, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(210, 623, 87, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(130, 630, 71, 22))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "                                 Send", None))
        self.checkBox.setText(_translate("MainWindow", "HEX", None))
        self.pushButton.setText(_translate("MainWindow", "Send", None))
        self.label.setText(_translate("MainWindow", " Path", None))
        self.pushButton_11.setText(_translate("MainWindow", "Browse", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "   Serial", None))
        self.label_7.setText(_translate("MainWindow", "Name", None))
        self.label_8.setText(_translate("MainWindow", "Baud", None))
        self.label_9.setText(_translate("MainWindow", "Data size", None))
        self.label_10.setText(_translate("MainWindow", "Parity", None))
        self.label_11.setText(_translate("MainWindow", "Handshake", None))
        self.label_12.setText(_translate("MainWindow", "Mode", None))
        self.Open_3.setText(_translate("MainWindow", "Open", None))
        self.pushButton_5.setText(_translate("MainWindow", "Serial", None))
        self.comboBox.setItemText(0, _translate("MainWindow", ".HS", None))
        self.comboBox.setItemText(1, _translate("MainWindow", ".txt", None))
        self.comboBox.setItemText(2, _translate("MainWindow", ".LBL", None))
        self.comboBox.setItemText(3, _translate("MainWindow", ".BAR1", None))
        self.comboBox.setItemText(4, _translate("MainWindow", ".xls", None))
        self.comboBox.setItemText(5, _translate("MainWindow", ".BAR2", None))
        self.comboBox.setItemText(6, _translate("MainWindow", ".hrn", None))
        self.label_3.setText(_translate("MainWindow", "File Type:", None))

